graphviz/main/default/objects/Graphviz_AutoBuild__mdt/Graphviz_AutoBuild__mdt.object-meta.xml
<CustomObject>
    <description>Autobuild metadata records are loaded in the Diagram Lightning UI as types of AutoBuilds i.e. options in the select list.

In Apex they are translated into AutoBuild.BuilderSourceType instances so must have all fields used in the constructor for that class.</description>
    <label>Graphviz AutoBuild</label>
    <pluralLabel>Graphviz AutoBuilds</pluralLabel>
</CustomObject>

graphviz/main/default/objects/Graphviz_AutoBuild__mdt/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>The name of the Apex class that implements the AutoBuilder interface</description>
    <label>Apex Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

graphviz/main/default/objects/Graphviz_AutoBuild__mdt/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The description displayed to the user in the UI.</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

graphviz/main/default/objects/Graphviz_AutoBuild__mdt/fields/Lightning_Config_Component__c.field-meta.xml
<CustomField>
    <fullName>Lightning_Config_Component__c</fullName>
    <description>The name of the component used to collect data before initiating an auto-build. If empty, no data will be collected.</description>
    <label>Lightning Config Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

graphviz/main/default/classes/BuilderSourceType.cls
public Class BuilderSourceType{
    @AuraEnabled
    public String sourceType;
    @AuraEnabled
    public String label;
    @AuraEnabled
    public String description;
    @AuraEnabled
    public String apexClass;
    @AuraEnabled
    public String configComponent;
    public BuilderSourceType(Graphviz_AutoBuild__mdt metaData) {
        this.sourceType = metaData.DeveloperName;
        this.label = metaData.Label;
        this.description = metaData.Description__c;
        this.apexClass = metaData.Apex_Class__c;
        this.configComponent = metaData.Lightning_Config_Component__c;
    }
}